[profile.default]
src = "/home/absystem/opensource/smart-contract-sanctuary-ethereum/contracts/mainnet"
out = "out"
libs = ["lib"]
remappings = [
  "contracts/=/home/absystem/opensource/smart-contract-sanctuary-ethereum/contracts/mainnet" 
  # Maps "contracts/" to the actual path where contracts are located
]

# Enable optimizer settings
optimizer = true
optimizer_runs = 200

