ethereum:
  ethereum_repo: "https://github.com/tintinweb/smart-contract-sanctuary-ethereum/contracts/mainnet"
  chain_id: 1 # Ethereum Mainnet
  sourcify_repo: "https://repo.sourcify.dev/api/contracts"
