ethereum_repo: "/home/abcode/opensource/smart-contract-sanctuary-ethereum/contracts/mainnet"
chain_id: 1 # Ethereum Mainnet
sourcify_repo: "https://repo.sourcify.dev/api/contracts"
# Add these configurations
batch_size: 10
max_retries: 3
verification_delay: 5000 # ms between verifications
