ethereum_repo: "/home/abcode/opensource/smart-contract-sanctuary-ethereum/contracts/mainnet"
chain_id: 1 # Ethereum Mainnet
sourcify_api: "https://sourcify.dev/api" # Changed from /server to /api
sourcify_repo: "https://repo.sourcify.dev/contracts" # Added /contracts
batch_size: 10
max_retries: 3
verification_delay: 5000 # ms between verifications

