ethereum_repo: "/home/abcode/opensource/smart-contract-sanctuary-ethereum/contracts/mainnet"
chain_id: "1" # Ethereum Mainnet - must be a string
sourcify_api: "https://sourcify.dev/server"
sourcify_repo: "https://repo.sourcify.dev"
batch_size: 10
max_retries: 3
verification_delay: 5000 # ms between verifications

